[cas]
export_url = "https://combot.org/api/cas/export.csv"
check_url = "https://combot.org/api/cas/check?user_id=%d"
local_file = "/tmp/your_file.json"

[telegram]
token = "YOUR:TELEGRAMBOTTOKEN"
timeout = 60
debug = false

[commands]
start = "/start"

[messages]
hello = "Hello!"
blocked = "User %s is blocked!"

[errors]
unknown = "Unknown error! Please contact the developer!"
